//! Proxy request session helpers.
//!
//! This is the transport-agnostic subset of cc-switch `proxy/session.rs`. The
//! proxy uses it to keep multi-turn request context stable for prompt cache
//! keys, Gemini Native shadow replay, and usage log correlation.

use axum::http::HeaderMap;
use serde_json::Value;
use uuid::Uuid;

/// Session ID source.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionIdSource {
    /// Extracted from `metadata.user_id` with a `_session_` marker.
    MetadataUserId,
    /// Extracted from `metadata.session_id`.
    MetadataSessionId,
    /// Extracted from request headers.
    Header,
    /// Generated by the proxy.
    Generated,
}

/// Session ID extraction result.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionIdResult {
    pub session_id: String,
    pub source: SessionIdSource,
    pub client_provided: bool,
}

/// Extract or generate a stable session ID for a proxy request.
///
/// Claude requests prefer Claude Code headers, then metadata. Codex/OpenAI
/// requests prefer Codex session headers, then metadata. Other formats use the
/// shared metadata fallback and finally a generated UUID.
pub fn extract_session_id(
    headers: &HeaderMap,
    body: &Value,
    client_format: &str,
) -> SessionIdResult {
    if client_format == "claude" {
        if let Some(result) = extract_claude_session(headers, body) {
            return result;
        }
    }

    if client_format == "codex" || client_format == "openai" {
        if let Some(result) = extract_codex_session(headers, body) {
            return result;
        }
    }

    if let Some(result) = extract_from_metadata(body) {
        return result;
    }

    generate_new_session_id()
}

fn extract_claude_session(headers: &HeaderMap, body: &Value) -> Option<SessionIdResult> {
    for header_name in ["x-claude-code-session-id", "claude-code-session-id"] {
        if let Some(session_id) = headers
            .get(header_name)
            .and_then(|value| value.to_str().ok())
            .map(str::trim)
            .filter(|value| !value.is_empty())
        {
            return Some(SessionIdResult {
                session_id: session_id.to_string(),
                source: SessionIdSource::Header,
                client_provided: true,
            });
        }
    }

    extract_from_metadata(body)
}

fn extract_codex_session(headers: &HeaderMap, body: &Value) -> Option<SessionIdResult> {
    for header_name in ["session_id", "x-session-id"] {
        if let Some(session_id) = headers
            .get(header_name)
            .and_then(|value| value.to_str().ok())
            .map(str::trim)
            .filter(|value| value.len() > 20)
        {
            return Some(SessionIdResult {
                session_id: format!("codex_{session_id}"),
                source: SessionIdSource::Header,
                client_provided: true,
            });
        }
    }

    if let Some(session_id) = body
        .get("metadata")
        .and_then(|metadata| metadata.get("session_id"))
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| value.len() > 10)
    {
        return Some(SessionIdResult {
            session_id: format!("codex_{session_id}"),
            source: SessionIdSource::MetadataSessionId,
            client_provided: true,
        });
    }

    None
}

fn extract_from_metadata(body: &Value) -> Option<SessionIdResult> {
    let metadata = body.get("metadata")?;

    if let Some(session_id) = metadata
        .get("user_id")
        .and_then(Value::as_str)
        .and_then(parse_session_from_user_id)
    {
        return Some(SessionIdResult {
            session_id,
            source: SessionIdSource::MetadataUserId,
            client_provided: true,
        });
    }

    if let Some(session_id) = metadata
        .get("session_id")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
    {
        return Some(SessionIdResult {
            session_id: session_id.to_string(),
            source: SessionIdSource::MetadataSessionId,
            client_provided: true,
        });
    }

    None
}

pub(crate) fn parse_session_from_user_id(user_id: &str) -> Option<String> {
    let pos = user_id.find("_session_")?;
    let session_id = &user_id[pos + "_session_".len()..];
    (!session_id.is_empty()).then(|| session_id.to_string())
}

fn generate_new_session_id() -> SessionIdResult {
    SessionIdResult {
        session_id: Uuid::new_v4().to_string(),
        source: SessionIdSource::Generated,
        client_provided: false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::HeaderValue;
    use serde_json::json;

    #[test]
    fn extracts_claude_header_before_metadata() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "x-claude-code-session-id",
            HeaderValue::from_static("header-session"),
        );
        let body = json!({ "metadata": { "session_id": "metadata-session" } });

        let result = extract_session_id(&headers, &body, "claude");

        assert_eq!(result.session_id, "header-session");
        assert_eq!(result.source, SessionIdSource::Header);
        assert!(result.client_provided);
    }

    #[test]
    fn extracts_metadata_user_session_marker() {
        let headers = HeaderMap::new();
        let body = json!({ "metadata": { "user_id": "user_abc_session_turn-42" } });

        let result = extract_session_id(&headers, &body, "claude");

        assert_eq!(result.session_id, "turn-42");
        assert_eq!(result.source, SessionIdSource::MetadataUserId);
    }

    #[test]
    fn prefixes_codex_header_sessions() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "x-session-id",
            HeaderValue::from_static("123456789012345678901"),
        );

        let result = extract_session_id(&headers, &json!({}), "codex");

        assert_eq!(result.session_id, "codex_123456789012345678901");
        assert_eq!(result.source, SessionIdSource::Header);
    }

    #[test]
    fn generated_session_is_non_empty() {
        let result = extract_session_id(&HeaderMap::new(), &json!({}), "claude");

        assert_eq!(result.source, SessionIdSource::Generated);
        assert!(!result.session_id.is_empty());
        assert!(!result.client_provided);
    }
}
