//! Compiles the translation catalogs in `i18n/` into a static lookup table.
//!
//! Doing this at build time buys three things a runtime catalog cannot:
//!
//! * **Zero-allocation lookups.** Every string ends up as a `&'static str` in a
//!   flat array, so the UI can build `SharedString::new_static` for it. A
//!   runtime `HashMap<String, String>` would allocate on every lookup, and the
//!   render loop performs thousands per frame.
//! * **Unknown keys are compile errors.** Each key becomes a `const`, so a typo
//!   or a stale key fails the build rather than rendering a blank label.
//! * **Locale drift is a compile error.** A key missing from a locale, or whose
//!   placeholders disagree between locales, stops the build here.
//!
//! `zh-Hans` is the reference catalog: it defines the key set, and the others
//! are checked against it.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// Catalog file stem paired with the generated table name. Adding a language
/// means adding one entry here, one `.toml` file, and one `Locale` variant in
/// `ochub_core::i18n` — no call sites change.
const LOCALES: &[(&str, &str)] = &[("zh-Hans", "ZH"), ("en", "EN"), ("ja", "JA")];

/// The catalog that defines which keys must exist.
const REFERENCE: &str = "zh-Hans";

fn main() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("i18n");
    println!("cargo:rerun-if-changed={}", dir.display());

    let catalogs: BTreeMap<&str, BTreeMap<String, String>> = LOCALES
        .iter()
        .map(|(stem, _)| (*stem, read_catalog(&dir.join(format!("{stem}.toml")))))
        .collect();

    let reference = &catalogs[REFERENCE];
    let mut errors = Vec::new();

    for (stem, catalog) in &catalogs {
        if *stem == REFERENCE {
            continue;
        }
        for key in catalog.keys() {
            if !reference.contains_key(key) {
                errors.push(format!("{stem}.toml: key `{key}` is not in {REFERENCE}.toml"));
            }
        }
        for (key, reference_text) in reference {
            match catalog.get(key) {
                None => errors.push(format!("{stem}.toml: missing key `{key}`")),
                Some(text) => {
                    let expected = placeholders(reference_text);
                    let actual = placeholders(text);
                    if expected != actual {
                        errors.push(format!(
                            "{stem}.toml: key `{key}` has placeholders {actual:?}, but {REFERENCE} has {expected:?}"
                        ));
                    }
                }
            }
        }
    }

    if !errors.is_empty() {
        for error in &errors {
            println!("cargo:warning={error}");
        }
        panic!(
            "{} translation catalog error(s); see the warnings above",
            errors.len()
        );
    }

    let keys: Vec<&String> = reference.keys().collect();
    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from crates/app/i18n/*.toml — do not edit.\n\n\
         /// A translation key. Values come from [`crate::i18n::k`]; the inner\n\
         /// index is an implementation detail of the generated table.\n\
         #[derive(Clone, Copy, PartialEq, Eq, Debug)]\n\
         pub struct Key(u16);\n\n\
         impl Key {\n    \
             pub(crate) const fn index(self) -> usize { self.0 as usize }\n\
         }\n\n",
    );
    out.push_str(&format!("pub(crate) const COUNT: usize = {};\n\n", keys.len()));

    for (stem, table) in LOCALES {
        let catalog = &catalogs[stem];
        out.push_str(&format!(
            "pub(crate) static {table}: [&str; COUNT] = [\n"
        ));
        for key in &keys {
            let text = catalog.get(*key).unwrap_or_else(|| &reference[*key]);
            out.push_str(&format!("    {},\n", quote(text)));
        }
        out.push_str("];\n\n");
    }

    out.push_str("/// Every translation key, as a compile-time constant.\npub mod k {\n    use super::Key;\n");
    let mut seen = BTreeSet::new();
    for (index, key) in keys.iter().enumerate() {
        let ident = to_ident(key);
        if !seen.insert(ident.clone()) {
            panic!("two catalog keys collapse to the same Rust identifier `{ident}`");
        }
        out.push_str(&format!(
            "    /// `{}`\n    pub const {ident}: Key = Key({index});\n",
            key.replace('`', "'")
        ));
    }
    out.push_str("}\n\n");

    out.push_str("#[cfg(test)]\npub(crate) static KEY_NAMES: [&str; COUNT] = [\n");
    for key in &keys {
        out.push_str(&format!("    {},\n", quote(key)));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("i18n_generated.rs");
    std::fs::write(&dest, out).expect("write generated catalog");
}

fn read_catalog(path: &Path) -> BTreeMap<String, String> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    toml::from_str::<BTreeMap<String, String>>(&text).unwrap_or_else(|err| {
        panic!(
            "failed to parse {} (every entry must be `\"key\" = \"text\"`): {err}",
            path.display()
        )
    })
}

/// The set of `{name}` placeholders in a template, ignoring `{{`/`}}` escapes.
fn placeholders(template: &str) -> BTreeSet<String> {
    let mut found = BTreeSet::new();
    let bytes: Vec<char> = template.chars().collect();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            '{' if bytes.get(i + 1) == Some(&'{') => i += 2,
            '}' if bytes.get(i + 1) == Some(&'}') => i += 2,
            '{' => {
                let start = i + 1;
                let mut end = start;
                while end < bytes.len() && bytes[end] != '}' {
                    end += 1;
                }
                if end < bytes.len() {
                    found.insert(bytes[start..end].iter().collect());
                }
                i = end + 1;
            }
            _ => i += 1,
        }
    }
    found
}

/// `settings.basic.tray.label` -> `SETTINGS_BASIC_TRAY_LABEL`
fn to_ident(key: &str) -> String {
    let ident: String = key
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if ident.starts_with(|c: char| c.is_ascii_digit()) {
        format!("K_{ident}")
    } else {
        ident
    }
}

fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
